ENTRY_POINTS = {
    "ArenaTAS_P": ["CraterToArenaTAS"],
    "Arena_P": ["CraterToArena"],
    "AridNexus_P": ["StockadeToAridNexus"],
    "Ash_P": ["CraterLakeToAsh", "FinalBossAscentToAsh", "FyrestoneToAsh", "InterludeToAsh", "RobotSlaughterToAsh", "VolcanoToAsh"],
    "Backburner_P": ["OldDustToBackburner", "SanctIntroToBackburner"],
    "Backdoor_P": ["CraterToBackdoor"],
    "BanditSlaughter_P": ["FridgeToBanditSlaughter"],
    "Beatdown2_P": ["PyroPetesToBeatdown2"],
    "Beatdown_P": ["CraterToBeatdown", "PyroPeteToBeatdown", "PyroPetesToBeatdown"],
    "BossCliffs_P": ["CliffsToBossCliffs", "VOGsChamberToBossCliffs"],
    "CastleExteriorFake_P": ["CastleKeepToCastleExteriorFake"],
    "CastleExterior_P": ["DungeonToCastleExterior", "DungeonsToCastleExterior", "MinesToCastleExterior"],
    "CastleKeepFak_P": ["CastleExteriorToCastleKeepFak"],
    "CastleKeep_P": ["DungeonToCastleKeep", "DungeonsToCastleKeep"],
    "Caverns_P": ["SanctuaryHoleToCaverns"],
    "Cliffs_P": ["BossCliffsToCliffs", "GrassToCliffs", "ShipToCliffs", "ThresherRaidToCliffs", "UndergroundToCliffs"],
    "Cove_P": ["WaterfrontToCove"],
    "CraterLake_P": ["AshToCraterLake"],
    "Crater_P": ["ArenaTASToCrater", "ArenaToCrater", "BackdoorToCrater", "BeatdownToCrater", "ForgeToCrater", "KickedOutToCrater", "MammaToCrater", "MoxxiToCrater"],
    "CreatureSlaughter_P": ["PandoraParkToCreatureSlaughter"],
    "DLC_P": ["InterludeToDLC"],
    "Dam_P": ["IceToDam"],
    "DarkForest_P": ["DeadForestToDarkForest", "MinesToDarkForest", "VillageToDarkForest"],
    "DeadForest_P": ["DarkForestToDeadForest", "MinesToDeadForest"],
    "Docks_P": ["VillageToDocks"],
    "DungeonRaid_P": ["DungeonToDungeonRaid", "DungeonsToDungeonRaid"],
    "Dungeon_P": ["CastleExteriorToDungeon", "CastleKeepToDungeon", "DungeonRaidToDungeon"],
    "Dungeons_P": ["CastleExteriorToDungeons", "CastleKeepToDungeons", "DungeonRaidToDungeons"],
    "FinalBossAscent_P": ["AshToFinalBossAscent", "VolcanoToFinalBossAscent"],
    "Forge_P": ["CraterToForge"],
    "Fridge_P": ["BanditSlaughterToFridge", "GrassToFridge", "IceToFridge", "OutwashToFridge"],
    "Frost2_P": ["IceToFrost2"],
    "Fyrestone_P": ["AshToFyrestone"],
    "Glacial_P": ["WaterfrontToGlacial"],
    "GrassRoad_P": ["OutwashToGrassRoad"],
    "Grass_P": ["CliffsToGrass", "FridgeToGrass", "HyperionCityToGrass", "InterludeToGrass", "LuckysToGrass", "OutwashToGrass", "PandoraParkToGrass"],
    "Helios_P": ["SandwormCavernToHelios"],
    "HypInter_P": ["InterludeToHypInter"],
    "HyperionCity_P": ["GrassToHyperionCity"],
    "Ice2_P": ["FrostToIce2"],
    "IceCanyon_P": ["IceToIceCanyon"],
    "Ice_P": ["DamToIce", "FridgeToIce", "FrostToIce", "IceCanyonToIce", "InterludeToIce", "SanctuaryHoleToIce", "SanctuaryToIce", "SouthpawFactoryToIce", "TundraExpressToIce", "WaterfrontDocksToIce", "WaterfrontToIce"],
    "Interlude_P": ["AshToInterlude", "GrassToInterlude", "HypInterToInterlude", "IceToInterlude", "LynchwoodToInterlude"],
    "KickedOut_P": ["CraterToKickedOut"],
    "Luckys_P": ["GrassToLuckys"],
    "Lynchwood_P": ["InterludeToLynchwood"],
    "Mamma_P": ["CraterToMamma"],
    "Mines_P": ["CastleExteriorToMines", "DarkForestToMines", "DeadForestToMines", "VillageToMines"],
    "Moxxi_P": ["CraterToMoxxi"],
    "OldDust_P": ["BackburnerToOldDust", "ResearchCenterToOldDust", "SandwormCavernToOldDust"],
    "Outwash_P": ["GrassRoadToOutwash"],
    "PandoraPark_P": ["CreatureSlaughterToPandoraPark", "GrassToPandoraPark"],
    "PowerStation_P": ["RockForestToPowerStation", "UndergroundToPowerStation"],
    "RaidBoss_P": ["SandwormCavernToRaidBoss"],
    "Refinery_P": ["SaltFlatsToRefinery"],
    "ResearchCenter_P": ["OldDustToResearchCenter", "SanctuaryToResearchCenter"],
    "RobotSlaughter_P": ["AshToRobotSlaughter"],
    "RockForest_P": ["PowerStationToRockForest", "UndergroundToRockForest"],
    "SaltFlats_P": ["RefineryToSaltFlats", "ShipGraveyardToSaltFlats", "SpireToSaltFlats", "WormBellyToSaltFlats"],
    "SanctIntro_P": ["BackburnerToSanctIntro"],
    "SanctuaryHole_P": ["CavernsToSanctuaryHole", "IceToSanctuaryHole"],
    "Sanctuary_P": ["IceToSanctuary", "ResearchCenterToSanctuary", "VOGsChamberToSanctuary"],
    "SandwormCavern_P": ["HeliosToSandwormCavern", "OldDustToSandwormCavern", "RaidBossToSandwormCavern"],
    "ShipGraveyard_P": ["SaltFlatsToShipGraveyard"],
    "Ship_P": ["CliffsToShip"],
    "SouthpawFactory_P": ["IceToSouthpawFactory"],
    "Spire_P": ["SaltFlatsToSpire"],
    "Stockade_P": ["AridNexusToStockade"],
    "TempleOfSlaughter_P": ["VillageToTempleOfSlaughter"],
    "ThresherRaid_P": ["CliffsToThresherRaid"],
    "TundraExpress_P": ["IceToTundraExpress", "WilhelmToTundraExpress"],
    "Underground_P": ["CliffsToUnderground", "CliffsToUnderground", "PowerStationToUnderground", "PowerStationToUnderground", "RockForestToUnderground"],
    "VOGsChamber_P": ["BossCliffsToVOGsChamber", "SanctuaryToVOGsChamber"],
    "Village_P": ["DarkForestToVillage", "DocksToVillage", "RockForestToVillage", "TempleOfSlaughterToVillage"],
    "Volcano_P": ["AshToVolcano", "FinalBossAscentToVolcano"],
    "Waterfront_P": ["CoveToWaterfront", "GlacialToWaterfront", "IceToWaterfront"],
    "Wilhelm_P": ["TundraExpressToWilhelm"],
    "WormBelly_P": ["SaltFlatsToWormBelly"],
}
