[tool.willow_mod]
name = "LoadZoneRandomizer"
version = "1.0.0"
description = "Shuffles all doors to have a random matching pair, works like Elden Ring's Fog Gate Randomizer"
author = "Sebb"
game = ["BL2"]
coop_support = "ClientSide"